eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id:xxxfghjfght  #注册中心上的客户端的描述
server:
  port: 8991
spring:
  application:
    name: service-member