spring:
  application:
    name: sercice-controller
    
#编写eureka配置 ，配置从哪个中心获取服务
#eureka:
#  client:
#    registerWithEureka: false    # 表示是否向 eureka服务注册中心注册自己,客户端当然不需要注册，客户访问的入口
#    serviceUrl:
#      defaultZone: http://localhost:81/eureka/,http://localhost:82/eureka/    
    