eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
#注册中心上的客户端的描述  
    instance-id:xxxfghjfght2  
server:
  port: 8992
spring:
  application:
    name: service-member
  zipkin:
    base-url: http://localhost:9411/     