eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
#注册中心上的客户端的描述  
    instance-id:xxxfghjfght  
server:
  port: 8997
spring:
  application:
    name: service-order
  zipkin:
    base-url: http://localhost:9411/      